config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    root                            to: 'home#index'
    resources :products,            only: %i[index show]
    resources :categories,          only: :show
    resources :orders,              only: %i[edit update] do
      post    :populate,            on: :collection
      delete  :remove_line_item,    on: :member
    end
    get '/cart',                    to: 'orders#edit', as: :cart
  end
end

app/models/potepan/option_value_decorator.rb
module Potepan::OptionValueDecorator
  def self.prepended(base)
    def base.filter_option_values_by(option_name, products)
      return [] if products.empty?

      joins(:option_type, option_values_variants: :variant)
        .where(
          'spree_option_types.name LIKE ? AND spree_variants.product_id IN (?)',
          "%#{option_name}%", products.ids
        )
        .distinct
    end
  end

  Spree::OptionValue.prepend self
end

app/models/potepan/order_decorator.rb
module Potepan::OrderDecorator
  # インスタンスレベル ================
  def display_tax_amount
    Spree::Money.new(adjustment_total, currency: currency)
  end

  Spree::Order.prepend self
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  include Constants::DefaultSize
  include Constants::SortType

  # クラスレベル ================
  def self.prepended(base)
    def base.new_arrival_from(from)
      where('available_on BETWEEN ? AND ?', from, Time.zone.now)
        .order(available_on: :desc)
        .includes(master: %i[images default_price])
    end

    def base.search_and_sort_and_filter_by(keyword:, color:, size:)
      includes(:variants, master: %i[images default_price])
        .eager_load(variants: %i[option_values_variants prices])
        .where(where_sentence(keyword, color, size))
        .distinct
    end

    def base.where_sentence(keyword, color, size)
      where_hash_base =
        { spree_products: { id: extract_products_from_keyword(keyword).ids } }
      return where_hash_base if color.nil? && size.nil?

      options = []
      options << color if color
      options << size  if size
      filterd_variant_ids =
        Spree::OptionValuesVariant
        .select(:variant_id)
        .where(option_value_id: options)
        .group(:variant_id)
        .having('COUNT(*) = ?', options.size)
      where_hash_base.merge!(
        spree_option_values_variants: { variant_id: filterd_variant_ids }
      )
    end

    def base.extract_products_from_keyword(keyword)
      meta_keyword =
        if keyword.start_with?('%') || keyword.end_with?('%')
          keyword
        else
          "%#{keyword}%"
        end

      where('name LIKE ? OR description LIKE ?', meta_keyword, meta_keyword)
    end

    def base.custom_order_products(products:, sort_type:)
      products.order(order_sentence(sort_type))
    end

    def base.order_sentence(sort_type = NEW_ARRIVAL)
      case sort_type.to_i
      when NEW_ARRIVAL
        'spree_products.available_on DESC'
      when PRICE_ASC
        'default_prices_spree_variants.amount ASC'
      when PRICE_DESC
        'default_prices_spree_variants.amount DESC'
      when OLDDER
        'spree_products.available_on ASC'
      else # フェールセーフ
        'spree_products.available_on DESC'
      end
    end
  end

  # インスタンスレベル ================
  def extract_similar_products
    return [] if taxon_ids.empty?

    Spree::Product.joins(:taxons)
                  .includes(master: %i[images default_price])
                  .where('spree_taxons.id IN (?) AND spree_products.id <> ?',
                         taxon_ids, id)
                  .distinct
                  .sample(MAX_SIMILAR_PRODUCTS)
  end

  Spree::Product.prepend self
end

app/models/potepan/taxon_decorator.rb
module Potepan::TaxonDecorator
  include Constants::DefaultSize
  include Constants::SortType

  # クラスレベル ================
  def self.prepended(base)
    def base.popular_taxons
      parent_ids = joins(:children).distinct.ids
      joins(:products).where.not(spree_taxons: { id: parent_ids })
                      .distinct
                      .sample(MAX_POPULAR_CATEGORY_PRODUCTS)
    end
  end

  # インスタンスレベル ================
  def products_sort_and_filter_by(color:, size:, sort_type:)
    Spree::Product
      .includes(:variants, master: %i[images default_price])
      .eager_load(variants: %i[option_values_variants prices])
      .where(where_sentence(color, size))
      .distinct
      .order(order_sentence(sort_type))
  end

  def where_sentence(color, size)
    where_hash_base = { spree_products: { id: product_ids } }
    return where_hash_base if color.nil? && size.nil?

    options = []
    options << color if color
    options << size  if size

    filterd_variant_ids =
      Spree::OptionValuesVariant
      .select(:variant_id)
      .where(option_value_id: options)
      .group(:variant_id)
      .having('COUNT(*) = ?', options.size)

    where_hash_base.merge!(
      spree_option_values_variants: { variant_id: filterd_variant_ids }
    )
  end

  def order_sentence(sort_type = NEW_ARRIVAL)
    case sort_type.to_i
    when NEW_ARRIVAL
      'spree_products.available_on DESC'
    when PRICE_ASC
      'default_prices_spree_variants.amount ASC'
    when PRICE_DESC
      'default_prices_spree_variants.amount DESC'
    when OLDDER
      'spree_products.available_on ASC'
    else # フェールセーフ
      'spree_products.available_on DESC'
    end
  end

  Spree::Taxon.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :query_params

  def show
    @taxon = Spree::Taxon.find_by!(id: params[:id])
    @products =
      @taxon.products_sort_and_filter_by(color: @filter_color,
                                         size: @filter_size,
                                         sort_type: params[:sort_type])
    respond_to do |format|
      format.html do
        @taxonomies = Spree::Taxonomy.all.includes(:root)
        @taxons = extract_taxons_from_taxonomies(@taxonomies)
        @filter_colors =
          Spree::OptionValue.filter_option_values_by(:color, @taxon.products)
        @filter_sizes  =
          Spree::OptionValue.filter_option_values_by(:size, @taxon.products)
      end
      format.js
    end
  end

  private

  def query_params
    @display_style = params[:display_style] == 'list' ? 'list' : 'grid'
    @filter_color  = params[:filter_color]
    @filter_size   = params[:filter_size]
  end

  def extract_taxons_from_taxonomies(taxonomies)
    taxonomies.map do |taxonomy|
      [taxonomy.id,
       Spree::Taxon.where(id: taxonomy.taxons.ids).includes(:children)]
    end.to_h
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  def index
    @new_arrival_products = Spree::Product.new_arrival_from(1.week.ago)
    @popular_taxons = Spree::Taxon.popular_taxons
  end
end

app/controllers/potepan/orders_controller.rb
# https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
require 'spree/core/controller_helpers/order'
require 'spree/core/controller_helpers/store'
require 'spree/core/controller_helpers/auth.rb'

class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Auth
  include Constants::DefaultSize

  before_action :set_order_and_line_items, only: %i[edit remove_line_item]
  before_action :assigns_order, only: :update

  def edit; end

  def update
    if @order.contents.update_cart(order_params)
      flash[:success] = 'カートの内容を更新しました'
    else
      flash[:danger] = 'カートの更新に失敗しました'
    end
    redirect_to potepan_cart_path
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    variant = Spree::Variant.find_by!(id: params[:variant_id])
    quantity =
      params[:quantity].present? ? params[:quantity].to_i : MIN_ORDER_QUANTITY
    @order.contents.add(variant, quantity)
    redirect_to potepan_cart_path
  end

  def remove_line_item
    line_item = @line_items.find_by!(id: params[:line_item_id])
    @order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_path
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: %i[quantity id])
  end

  def assigns_order
    @order =
      current_order ||
      Spree::Order.incomplete.find_or_initialize_by(
        guest_token: cookies.signed[:guest_token]
      )
    return if @order

    redirect_to potepan_root_path
  end

  def set_order_and_line_items
    @order =
      current_order ||
      Spree::Order.incomplete.find_or_initialize_by(
        guest_token: cookies.signed[:guest_token]
      )
    @line_items = @order.line_items.includes(variant: :product)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  before_action :query_params
  before_action :redirect_to_root_when_keyword_blank, only: :index

  def index
    @products =
      Spree::Product.search_and_sort_and_filter_by(
        keyword: @keyword,
        color: @filter_color,
        size: @filter_size
      )
    @ordered_products =
      Spree::Product.custom_order_products(
        products: @products,
        sort_type: params[:sort_type]
      )
    respond_to do |format|
      format.html do
        @filter_colors =
          Spree::OptionValue.filter_option_values_by(:color, @products)
        @filter_sizes  =
          Spree::OptionValue.filter_option_values_by(:size, @products)
      end
      format.js
    end
  end

  def show
    @product = Spree::Product.find_by!(slug: params[:id])
    @variant = @product.variants.find_by(id: params[:variant_id]) ||
               @product.variants.first || @product
    @images  = @variant.images
    respond_to do |format|
      format.html { @similar_products = @product.extract_similar_products }
      format.js
    end
  end

  private

  def redirect_to_root_when_keyword_blank
    redirect_to potepan_root_path if params[:keyword].blank?
  end

  def query_params
    @display_style = params[:display_style] == 'list' ? 'list' : 'grid'
    @filter_color  = params[:filter_color]
    @filter_size   = params[:filter_size]
    @keyword       = params[:keyword]
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/views/potepan/orders/_line_item.html.erb
<% variant = line_item.variant %>
<%= form.fields_for :line_items, line_item do |field| %>
  <tr id="line-item-<%= variant.id %>" class="line-item">
    <td class="col-xs-2">
      <%= link_to(remove_line_item_potepan_order_path(order.id, line_item_id: line_item.id), method: :delete) do %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
      <span class="cartImage">
        <%= image_tag(variant.display_image.attachment(:product), alt: "image") %>
      </span>
    </td>
    <td class="col-xs-4">
      <%= link_to potepan_product_path(variant.product), class: 'cart-product-link' do %>
        <div><%= line_item.name %></div>
        <div><small><%= variant.options_text %></small></div>
      <% end %>
    </td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2">
      <%= field.number_field :quantity, min: 1, max: 99, value: line_item.quantity %>
    </td>
    <td class="col-xs-2"><%= line_item.display_amount %></td>
  </tr>
<% end %>

app/views/potepan/orders/edit.html.erb
<% provide(:title, "cart") %>
<% order_and_line_items_present = (@order.present? && @line_items.present?) %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeaderImage">
    <div class="container">
      <div class="tableBlock">
        <div class="row tableInner">
          <div class="col-xs-12">
            <div class="page-title">
              <h2>cart</h2>
              <ol class="breadcrumb">
                <li>
                  <a href="<%= potepan_root_path %>">Home</a>
                </li>
                <li class="active">cart</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix cartListWrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <% if order_and_line_items_present %>
            <div class="cartListInner">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th></th>
                      <th>商品名</th>
                      <th>価格</th>
                      <th>数</th>
                      <th>小計</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= form_with model: @order, url: potepan_order_path(@order), id: "cart-update-form", local: true do |form| %>
                      <%= render partial: 'line_item', collection: @line_items, locals: { order: @order, form: form } %>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="updateArea">
                <span onclick="FormSubmit('cart-update-form');" class="btn" id="update-btn">アップデート</span>
              </div>
              <div class="totalAmountArea">
                <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                  <ul class="list-unstyled">
                    <li>小計 <span class="itemTotal"><%= @order.display_item_total %></span></li>
                    <li>消費税 <span class="taxAmount"><%= @order.display_tax_amount %></span></li>
                    <li>総計 <span class="grandTotal"><%= @order.display_total %></span></li>
                  </ul>
                </div>
              </div>
              <div class="checkBtnArea">
                <a href="#" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right"
                    aria-hidden="true"></i></a>
              </div>
            </div>
          <% else %>
            <h5>カートに商品はありません</h5>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>