config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    root                            to: 'home#index'
    resources :products,            only: %i[index show]
    resources :categories,          only: :show
    resources :orders,              only: %i[edit update] do
      post    :populate,            on: :collection
      delete  :remove_line_item,    on: :member
    end
    get '/cart',                    to: 'orders#edit', as: :cart
  end
end

app/models/potepan/option_value_decorator.rb
module Potepan::OptionValueDecorator
  def self.prepended(base)
    def base.filter_option_values_by(option_name, products)
      return [] if products.empty?

      joins(:option_type, option_values_variants: :variant)
        .where(
          'spree_option_types.name LIKE ? AND spree_variants.product_id IN (?)',
          "%#{option_name}%", products.ids
        )
        .distinct
    end
  end

  Spree::OptionValue.prepend self
end

app/models/potepan/order_decorator.rb
module Potepan::OrderDecorator
  # インスタンスレベル ================
  def display_tax_amount
    Spree::Money.new(adjustment_total, currency: currency)
  end

  Spree::Order.prepend self
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  include Constants::DefaultSize
  include Constants::SortType

  # クラスレベル ================
  def self.prepended(base)
    def base.new_arrival_from(from)
      where('available_on BETWEEN ? AND ?', from, Time.zone.now)
        .order(available_on: :desc)
        .includes(master: %i[images default_price])
    end

    def base.search_and_sort_and_filter_by(keyword:, color:, size:)
      includes(:variants, master: %i[images default_price])
        .eager_load(variants: %i[option_values_variants prices])
        .where(where_sentence(keyword, color, size))
        .distinct
    end

    def base.where_sentence(keyword, color, size)
      where_hash_base =
        { spree_products: { id: extract_products_from_keyword(keyword).ids } }
      return where_hash_base if color.nil? && size.nil?

      options = []
      options << color if color
      options << size  if size
      filterd_variant_ids =
        Spree::OptionValuesVariant
        .select(:variant_id)
        .where(option_value_id: options)
        .group(:variant_id)
        .having('COUNT(*) = ?', options.size)
      where_hash_base.merge!(
        spree_option_values_variants: { variant_id: filterd_variant_ids }
      )
    end

    def base.extract_products_from_keyword(keyword)
      meta_keyword =
        if keyword.start_with?('%') || keyword.end_with?('%')
          keyword
        else
          "%#{keyword}%"
        end

      where('name LIKE ? OR description LIKE ?', meta_keyword, meta_keyword)
    end

    def base.custom_order_products(products:, sort_type:)
      products.order(order_sentence(sort_type))
    end

    def base.order_sentence(sort_type = NEW_ARRIVAL)
      case sort_type.to_i
      when NEW_ARRIVAL
        'spree_products.available_on DESC'
      when PRICE_ASC
        'default_prices_spree_variants.amount ASC'
      when PRICE_DESC
        'default_prices_spree_variants.amount DESC'
      when OLDDER
        'spree_products.available_on ASC'
      else # フェールセーフ
        'spree_products.available_on DESC'
      end
    end
  end

  # インスタンスレベル ================
  def extract_similar_products
    return [] if taxon_ids.empty?

    Spree::Product.joins(:taxons)
                  .includes(master: %i[images default_price])
                  .where('spree_taxons.id IN (?) AND spree_products.id <> ?',
                         taxon_ids, id)
                  .distinct
                  .sample(MAX_SIMILAR_PRODUCTS)
  end

  Spree::Product.prepend self
end

app/models/potepan/taxon_decorator.rb
module Potepan::TaxonDecorator
  include Constants::DefaultSize
  include Constants::SortType

  # クラスレベル ================
  def self.prepended(base)
    def base.popular_taxons
      parent_ids = joins(:children).distinct.ids
      joins(:products).where.not(spree_taxons: { id: parent_ids })
                      .distinct
                      .sample(MAX_POPULAR_CATEGORY_PRODUCTS)
    end
  end

  # インスタンスレベル ================
  def products_sort_and_filter_by(color:, size:, sort_type:)
    Spree::Product
      .includes(:variants, master: %i[images default_price])
      .eager_load(variants: %i[option_values_variants prices])
      .where(where_sentence(color, size))
      .distinct
      .order(order_sentence(sort_type))
  end

  def where_sentence(color, size)
    where_hash_base = { spree_products: { id: product_ids } }
    return where_hash_base if color.nil? && size.nil?

    options = []
    options << color if color
    options << size  if size

    filterd_variant_ids =
      Spree::OptionValuesVariant
      .select(:variant_id)
      .where(option_value_id: options)
      .group(:variant_id)
      .having('COUNT(*) = ?', options.size)

    where_hash_base.merge!(
      spree_option_values_variants: { variant_id: filterd_variant_ids }
    )
  end

  def order_sentence(sort_type = NEW_ARRIVAL)
    case sort_type.to_i
    when NEW_ARRIVAL
      'spree_products.available_on DESC'
    when PRICE_ASC
      'default_prices_spree_variants.amount ASC'
    when PRICE_DESC
      'default_prices_spree_variants.amount DESC'
    when OLDDER
      'spree_products.available_on ASC'
    else # フェールセーフ
      'spree_products.available_on DESC'
    end
  end

  Spree::Taxon.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :query_params

  def show
    @taxon = Spree::Taxon.find_by!(id: params[:id])
    @products =
      @taxon.products_sort_and_filter_by(color: @filter_color,
                                         size: @filter_size,
                                         sort_type: params[:sort_type])
    respond_to do |format|
      format.html do
        @taxonomies = Spree::Taxonomy.all.includes(:root)
        @taxons = extract_taxons_from_taxonomies(@taxonomies)
        @filter_colors =
          Spree::OptionValue.filter_option_values_by(:color, @taxon.products)
        @filter_sizes  =
          Spree::OptionValue.filter_option_values_by(:size, @taxon.products)
      end
      format.js
    end
  end

  private

  def query_params
    @display_style = params[:display_style] == 'list' ? 'list' : 'grid'
    @filter_color  = params[:filter_color]
    @filter_size   = params[:filter_size]
  end

  def extract_taxons_from_taxonomies(taxonomies)
    taxonomies.map do |taxonomy|
      [taxonomy.id,
       Spree::Taxon.where(id: taxonomy.taxons.ids).includes(:children)]
    end.to_h
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  def index
    @new_arrival_products = Spree::Product.new_arrival_from(1.week.ago)
    @popular_taxons = Spree::Taxon.popular_taxons
  end
end

app/controllers/potepan/orders_controller.rb
# https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb
require 'spree/core/controller_helpers/order'
require 'spree/core/controller_helpers/store'
require 'spree/core/controller_helpers/auth.rb'

class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Auth
  include Constants::DefaultSize

  before_action :set_order_and_line_items, only: %i[edit remove_line_item]
  before_action :assigns_order, only: :update

  def edit; end

  def update
    if @order.contents.update_cart(order_params)
      flash[:success] = 'カートの内容を更新しました'
    else
      flash[:danger] = 'カートの更新に失敗しました'
    end
    redirect_to potepan_cart_path
  end

  def populate
    @order = current_order(create_order_if_necessary: true)
    variant = Spree::Variant.find_by!(id: params[:variant_id])
    quantity =
      params[:quantity].present? ? params[:quantity].to_i : MIN_ORDER_QUANTITY
    @order.contents.add(variant, quantity)
    redirect_to potepan_cart_path
  end

  def remove_line_item
    line_item = @line_items.find_by!(id: params[:line_item_id])
    @order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_path
  end

  private

  def order_params
    params.require(:order).permit(line_items_attributes: %i[quantity id])
  end

  def assigns_order
    @order =
      current_order ||
      Spree::Order.incomplete.find_or_initialize_by(
        guest_token: cookies.signed[:guest_token]
      )
    return if @order

    redirect_to potepan_root_path
  end

  def set_order_and_line_items
    @order =
      current_order ||
      Spree::Order.incomplete.find_or_initialize_by(
        guest_token: cookies.signed[:guest_token]
      )
    @line_items = @order.line_items.includes(variant: :product)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  before_action :query_params
  before_action :redirect_to_root_when_keyword_blank, only: :index

  def index
    @products =
      Spree::Product.search_and_sort_and_filter_by(
        keyword: @keyword,
        color: @filter_color,
        size: @filter_size
      )
    @ordered_products =
      Spree::Product.custom_order_products(
        products: @products,
        sort_type: params[:sort_type]
      )
    respond_to do |format|
      format.html do
        @filter_colors =
          Spree::OptionValue.filter_option_values_by(:color, @products)
        @filter_sizes  =
          Spree::OptionValue.filter_option_values_by(:size, @products)
      end
      format.js
    end
  end

  def show
    @product = Spree::Product.find_by!(slug: params[:id])
    @variant = @product.variants.find_by(id: params[:variant_id]) ||
               @product.variants.first || @product
    @images  = @variant.images
    respond_to do |format|
      format.html { @similar_products = @product.extract_similar_products }
      format.js
    end
  end

  private

  def redirect_to_root_when_keyword_blank
    redirect_to potepan_root_path if params[:keyword].blank?
  end

  def query_params
    @display_style = params[:display_style] == 'list' ? 'list' : 'grid'
    @filter_color  = params[:filter_color]
    @filter_size   = params[:filter_size]
    @keyword       = params[:keyword]
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def amount_stock_items(variant)
    variant.stock_items.inject(0) do |result, stock_item|
      result + stock_item.count_on_hand
    end
  end

  def order_quantity_options(max_quantity:)
    quantity = []
    max_quantity.times do |index|
      quantity_num = index + 1
      quantity << [quantity_num, quantity_num]
    end
    quantity
  end
end

app/views/potepan/products/_image.html.erb
<% images.each_with_index do |image, index| %>
  <% add_class = "active" if index.zero? %>
  <div class="item <%= add_class %>" data-thumb="<%= index %>">
    <%= image_tag(image.attachment(:large)) %>
  </div>
<% end %>

app/views/potepan/products/_option_values.html.erb
<% if product.has_variants? %>
  <% product.variants.each do |variant| %>
    <option value="<%= variant.id %>">
      <%= variant.options_text %>
    </option>
  <% end %>
<% else %>
  <option value="<%= product.master.id %>">ALL</option>
<% end %>

app/views/potepan/products/_similar_product.html.erb
<%= link_to potepan_product_path(similar_product) do %>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(similar_product.display_image.attachment(:product), alt: "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= similar_product.name %></h5>
        <h3><%= similar_product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/products/_stock_items.html.erb
<% if (amaount_stock_items = amount_stock_items(variant)) > 0 %>
  残り <%= amaount_stock_items %> 点
<% else %>
  現在在庫切れ
<% end %>

app/views/potepan/products/_thumb.html.erb
<% images.each_with_index do |image, index| %>
  <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
    <%= image_tag(image.attachment(:product)) %>
  </div>
<% end %>

app/views/potepan/products/index.html.erb
<% provide(:title, "検索結果") %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <%= render 'potepan/shared/categories_and_search/top_section',  header_title: "検索条件：#{@keyword}",
                                                                  page_name: @keyword %>
  <!-- MAIN CONTENT SECTION -->
  <%= render 'potepan/shared/categories_and_search/main_content_section', taxonomies:    nil,
                                                                          taxons:        nil, 
                                                                          display_style: @display_style, 
                                                                          filter_colors: @filter_colors,
                                                                          filter_color:  @filter_color,
                                                                          filter_size:   @filter_size,
                                                                          filter_sizes:  @filter_sizes,
                                                                          taxon:         nil,
                                                                          products:      @ordered_products,
                                                                          keyword:       @keyword %>
  <!-- LIGHT SECTION -->
  <%= render 'potepan/shared/light_section' %>
</div>

app/views/potepan/products/index.js.erb
<% if @products.present? %>
  $("#show_products").html('<%= escape_javascript(render "potepan/shared/categories_and_search/display_#{@display_style}",  products:     @ordered_products,
                                                                                                                            filter_color: @filter_color, 
                                                                                                                            filter_size:  @filter_size) %>');
<% else %>
  $("#show_products").html('<h5>条件に合致する商品はありません</h5>');
<% end %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="main-wrapper">
  <!-- LIGHT SECTION -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <a href="<%= potepan_root_path %>">Home</a>
            </li>
            <li class="active"><%= @product.name %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <!-- MAIN CONTENT SECTION -->
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner" id="image-carousel-inner">
                  <%= render 'image', images: @images %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner" id="thumb-carousel-inner">
                    <%= render 'thumb', images: @images %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <ul class="list-inline">
                <li>
                  <% if @product.taxon_ids[0] %>
                    <a href="<%= potepan_category_path(@product.taxon_ids[0]) %>"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a>
                  <% end %>
                </li>
              </ul>
              <h2><%= @product.name %></h2>
              <h3><%= @variant.display_price %></h3>
              <p><%= @product.description %></p>
              <%= form_with scope: :order, url: populate_potepan_orders_path, local: true, id: 'cart-form' do %>
                <span class="quick-drop">
                  <select name="guiest_id3" id="guiest_id3" class="select-drop">
                    <%= render 'option_values', product: @product %>
                  </select>
                </span>
                <span class="quick-drop resizeWidth">
                  <%= select_tag(:quantity,
                    options_for_select(order_quantity_options(max_quantity: 10)),
                    id: "guiest_id4", class: "select-drop",) 
                  %>
                </span>
                <span class="stock">
                  <%= render 'stock_items', variant: @variant %>
                </span>
                <div id="hidden-variant-id">
                  <%= hidden_field_tag :variant_id, @variant.id %>
                </div>
                <div class="btn-area">
                  <span class="btn btn-primary btn-block order" onclick="FormSubmit('cart-form')">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></span>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row productsContent">
        <div class="col-xs-12">
          <div class="page-header">
            <h4>関連商品</h4>
          </div>
          <% if @similar_products.present? %>
            <%= render partial: 'similar_product', collection: @similar_products %>
          <% else %>
            <h5>この商品に関連する商品はありません</h5>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/potepan/products/show.js.erb
$("#image-carousel-inner").html("<%= escape_javascript(render 'image', images: @images) %>");
$("#thumb-carousel-inner").html("<%= escape_javascript(render 'thumb', images: @images) %>");
$(".media-body h3").html("<%= @variant.display_price %>");
$(".stock").html("<%= escape_javascript(render 'stock_items', variant: @variant) %>");
$("#hidden-variant-id").html("<%= escape_javascript(hidden_field_tag :variant_id, @variant.id) %>")