config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    root                            to: 'home#index'
    resources :products,            only: %i[index show]
    resources :categories,          only: :show
    resources :orders,              only: %i[edit update] do
      post    :populate,            on: :collection
      delete  :remove_line_item,    on: :member
    end
    get '/cart',                    to: 'orders#edit', as: :cart
  end
end

app/views/potepan/shared/categories_and_search/_display_grid.html.erb
<div class="row">
  <% products.each do |product| %>
    <%= link_to potepan_product_path(product) do %>
      <div class="col-sm-4 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment(:product), alt: "products-img") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
            <% if product.has_variants? %>
              <h6><%= variation_message(filter_color: filter_color, filter_size: filter_size) %></h6>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/potepan/shared/categories_and_search/_display_list.html.erb
<div class="row productListSingle">
  <% products.each do |product| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <%= image_tag(product.display_image.attachment(:product), class: "media-object", alt: "Image") %>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to product.name, potepan_product_path(product) %>
          </h4>
          <p><%= product.description %></p>
          <h3><%= product.display_price %></h3>
          <% if product.has_variants? %>
            <h6><%= variation_message(filter_color: filter_color, filter_size: filter_size) %></h6>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/shared/categories_and_search/_filter_color.html.erb
<% selected = (filter_color_now == filter_color.id.to_s) %>
<% params = { filter_color:   filter_color, 
              filter_size:    filter_size, 
              display_style:  display_style, 
              selected_color: selected, 
              selected_size:  false,
              keyword:        keyword } %>

<% if taxon.present? %>
  <% filter_color_link = potepan_category_path(filter_query_params(params))%>
<% else %>
  <% filter_color_link = potepan_products_path(filter_query_params(params)) %>
<% end %>
<li>
  <%= link_to filter_color_link do %>
    <%= filter_color.presentation %>
    <%= '✔︎' if selected %>
  <% end %>
</li>

app/views/potepan/shared/categories_and_search/_filter_size.html.erb
<% selected = (filter_size_now == filter_size.id.to_s) %>
<% params = { filter_color:   filter_color, 
              filter_size:    filter_size, 
              display_style:  display_style, 
              selected_color: false, 
              selected_size:  selected,
              keyword:        keyword } %>

<% if taxon.present? %>
  <% filter_size_link = potepan_category_path(filter_query_params(params)) %>
<% else %>
  <% filter_size_link = potepan_products_path(filter_query_params(params)) %>
<% end %>
<li>
  <%= link_to filter_size_link do %>
    <%= filter_size.presentation %>
    <%= '✔︎' if selected %>
  <% end %>
</li>

app/views/potepan/shared/categories_and_search/_main_content_section.html.erb
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <% if taxonomies.present? && taxons.present? %>
          <div class="panel panel-default">
            <div class="panel-heading">商品カテゴリー</div>
            <div class="panel-body">
              <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
                <ul class="nav navbar-nav side-nav">
                  <%= render 'potepan/categories/categories', taxonomies: taxonomies, taxons: taxons, display_style: display_style %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
        <div class="panel panel-default filterNormal" id="color-filter-panel">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <% if filter_colors.present? %>
                <%= render partial: 'potepan/shared/categories_and_search/filter_color', collection: filter_colors, locals: { filter_color_now: filter_color, 
                                                                                                                              filter_size:      filter_size, 
                                                                                                                              display_style:    display_style,
                                                                                                                              taxon:            taxon,
                                                                                                                              keyword:          keyword } %>
              <% else %>
                <li>色のオプションはありません</li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal" id="size-filter-panel">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <% if filter_sizes.present? %>
                <%= render partial: 'potepan/shared/categories_and_search/filter_size', collection: filter_sizes, locals: { filter_size_now: filter_size, 
                                                                                                                            filter_color:    filter_color, 
                                                                                                                            display_style:   display_style,
                                                                                                                            taxon:           taxon,
                                                                                                                            keyword:         keyword } %>
              <% else %>
                <li>サイズのオプションはありません</li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">新着順</option>
              <option value="1">安い順</option>
              <option value="2">高い順</option>
              <option value="3">古い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <% if taxon.present? %>
                <% grid_display_link = potepan_category_path(id: taxon.id, display_style: 'grid', filter_color: filter_color, filter_size: filter_size) %>
                <% list_display_link = potepan_category_path(id: taxon.id, display_style: 'list', filter_color: filter_color, filter_size: filter_size) %>
              <% else %>
                <% grid_display_link = potepan_products_path(keyword: keyword, display_style: 'grid', filter_color: filter_color, filter_size: filter_size) %>
                <% list_display_link = potepan_products_path(keyword: keyword, display_style: 'list', filter_color: filter_color, filter_size: filter_size) %>
              <% end %>
              <%= link_to grid_display_link do %>
                <button type="button" class="btn btn-default <%= display_style == 'grid' ? 'active' : '' %>">
                  <i class="fa fa-th" aria-hidden="true"></i>
                  <span>Grid</span>
                </button>
              <% end %>
              <%= link_to list_display_link do %>
                <button type="button" class="btn btn-default <%= display_style == 'list' ? 'active' : '' %>">
                  <i class="fa fa-th-list" aria-hidden="true"></i>
                  <span>List</span>
                </button>
              <% end %>
            </div>
          </div>
        </div>
        <div id="show_products">
          <% if products.present? %>
            <%= render "potepan/shared/categories_and_search/display_#{display_style}", products:     products, 
                                                                                        filter_color: filter_color, 
                                                                                        filter_size:  filter_size %>
          <% else %>
            <h5>条件に合致する商品はありません</h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/shared/categories_and_search/_top_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= header_title %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="<%= potepan_root_path %>">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= page_name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>