config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    root                            to: 'home#index'
    resources :products,            only: %i[index show]
    resources :categories,          only: :show
    resources :orders,              only: %i[edit update] do
      post    :populate,            on: :collection
      delete  :remove_line_item,    on: :member
    end
    get '/cart',                    to: 'orders#edit', as: :cart
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<title><%= full_page_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-search"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <%= form_with url: potepan_products_path, id: "search-form", method: :get, local: true do |f| %>
                  <li>
                    <span class="input-group">
                      <%= f.text_field :keyword, class: "form-control", placeholder: "Search…", aria: { describedby: "basic-addon2" } %>
                      <%= content_tag :span, "検索", class: 'input-group-addon addPointer', id: "basic-addon2", onclick: "FormSubmit('search-form');" %>
                    </span>
                  </li>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="<%= potepan_cart_path %>" class="dropdown-toggle" data-toggle="dropdown disabled" id="cart-page-link">
                <i class="fa fa-shopping-cart"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= potepan_root_path %>"><%= image_tag("img/logo.png", :alt => "") %></a>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= potepan_root_path %>">Home</a></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
              data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <!-- FLASH -->
  <%= render 'layouts/flash' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!--  HEAD  -->
    <%= render 'layouts/head' %>
  </head>
  <body>
    <!-- HEADER -->
    <%= render 'layouts/header' %>
    <!-- CONTENTS -->
    <%= yield %>
    <!-- FOOTER -->
    <%= render 'layouts/footer' %>
  </body>
</html>